function[] = fPlot_abh_FrDxHy(ah_nd55, ah_ud55, ah_dsp55, nax_dsp,...
    bh_nd55, bh_ud55,...
    err_ahx_dsp, err_ahx_nd, err_ahx_ud, ...
    err_Fx_ndp, err_Fx_udp, err_Fx_dsp,...
    Fr_ndp55, Fr_ndf55, Fr_udp55, Fr_udf55, Fx_dsp55, write2disc)
%% PREAMBLE
scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 30; % best for 1x1: 46
MarkerS = 10;
yPos = 0.825; % y position of the textbox
CapS = 7;

gray0 = [0.6 0.6 0.6];
gray1 = [0.6 0.6 0.6]; 
black = [0. 0. 0.]; 

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'v','^','diamond','o','<','square','>','none'};
lStyles = {'none','-',':','-.','--'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3) scrsz(4)/1.6]);
% 1 x 2 FIGURE with a) & b)
%% SUBPLOT a) pressurized
subplot1 = subplot(1,2,1,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0.:0.5:2,...
    'XTickLabel',{'0.0','0.5','1.0','1.5','2.0'},...
    'YTick',0.:0.5:2.,...
    'YTickLabel',{'0.0','0.5','1.0','1.5','2.0'},...
    'LineWidth', 1.5);
hold(subplot1,'all');
box(subplot1,'on');
grid(subplot1,'off');

xlim(subplot1,[0. 2]);
ylim(subplot1,[0. 2.]);


plot1(1) = plot(ah_nd55,Fr_ndp55,...
    'Marker','x','MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'LineStyle','none',...
    'DisplayName',['Schwindt et al. (2017)']);

plot1(numel(plot1)+1) = plot(ah_ud55,Fr_udp55,...
    'Marker','square','MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'LineStyle','none',...
    'DisplayName',['case 1.i']);

plot1(numel(plot1)+1) = plot(ah_dsp55(:,1),Fx_dsp55(:,1),...
    'Marker','diamond','MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'LineStyle','none',...
    'DisplayName',['case 1.ii']);


lgnd = legend(subplot1,'show','Location','NorthWest');
plot1(numel(plot1)+1) = plot(ah_dsp55(:,2),Fx_dsp55(:,2),...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'MarkerFaceColor',[1 1 1],...
    'LineStyle','none',...
    'DisplayName',['a_* = ', num2str(nax_dsp(2),'%-1.2f') ]);
plot1(numel(plot1)+1) = plot(ah_dsp55(:,3),Fx_dsp55(:,3),...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'MarkerFaceColor',[1 1 1],...
    'LineStyle','none',...
    'DisplayName',['a_* = ', num2str(nax_dsp(3),'%-1.2f')]);

% ERRORBAR PLOTTING
plot1(numel(plot1)+1) = errorbar(ah_nd55,Fr_ndp55,...
    -err_Fx_ndp,err_Fx_ndp,-err_ahx_nd,err_ahx_nd,...
    'Marker','x','MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'Color',gray0,...
    'LineStyle','none',...
    'CapSize',CapS);

plot1(numel(plot1)+1) = errorbar(ah_ud55,Fr_udp55,...
    -err_Fx_udp,err_Fx_udp,-err_ahx_ud,err_ahx_ud,...
    'Marker','square','MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'Color',gray0,...
    'LineStyle','none',...
    'CapSize',CapS);

plot1(numel(plot1)+1) = errorbar(ah_dsp55(:,1),Fx_dsp55(:,1),...
    -err_Fx_dsp(:,1),err_Fx_dsp(:,1),-err_ahx_dsp(:,1),err_ahx_dsp(:,1),...
    'Marker','diamond','MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'Color',gray0,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName',['a_* = ', num2str(nax_dsp(1),'%-1.2f') ]);
plot1(numel(plot1)+1) = errorbar(ah_dsp55(:,2),Fx_dsp55(:,2),...
    -err_Fx_dsp(:,2),err_Fx_dsp(:,2),-err_ahx_dsp(:,2),err_ahx_dsp(:,2),...
    'Marker','diamond','MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'Color',gray0,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName',['a_* = ', num2str(nax_dsp(2),'%-1.2f') ]);
plot1(numel(plot1)+1) = errorbar(ah_dsp55(:,3),Fx_dsp55(:,3),...
    -err_Fx_dsp(:,3),err_Fx_dsp(:,3),-err_ahx_dsp(:,3),err_ahx_dsp(:,3),...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'Color',gray0,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName',['a_* = ', num2str(nax_dsp(3),'%-1.2f')]);
% LINE UP
fMakeXgrid(0.5:0.5:1.5,[0.,2.],0.5);
fMakeYgrid([0,2],0.5:0.5:1.5,0.5);
% Create xlabel
xlabel('a_* / h_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Grain-related flow velocity F_* [-]',...
    'FontSize',fontS,...
    'FontName','Arial');
annotation(figure1,'textbox',...
        [0.40 yPos  0.4 0.1],... %0.425 [x_begin y_begin length height]org:0.14 yPos  0.4 0.1
        'String',{'a)'},...
        'FontName','Arial','FontSize',fontS,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');

%% SUBPLOT b) free surface flow
subplot2 = subplot(1,2,2,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0.:0.5:2,...
    'XTickLabel',{'0.0','0.5','1.0','1.5','2.0'},...
    'YTick',0:0.5:2,...
    'YTickLabel',{'0.0','0.5','1.0','1.5','2.0'},...
    'LineWidth', 1.5);

hold(subplot2,'all');
box(subplot2,'on');
grid(subplot2,'off');

xlim(subplot2,[0 2]);
ylim(subplot2,[0. 2]);

plot2(1) = plot(bh_nd55, Fr_ndf55,...
    'Color',black,...
    'LineStyle','none',...
    'Marker','+','MarkerSize',MarkerS,...
    'DisplayName','Schwindt et al. (2017)');

plot2(numel(plot1)+1) = plot(bh_ud55,Fr_udf55,...
    'Color',black,...
    'LineStyle','none',...
    'Marker','v','MarkerSize',MarkerS,...
    'DisplayName','case 1.i');

lgnd = legend(subplot2,'show','Location','NorthWest');

% regression curves - main
[X_nd, X_ud, Y_nd, Y_ud] = fRegMake_abhFx();
u_Fx_nd = fGetErrFrRel(Y_nd).*3;
u_Fx_ud = fGetErrFrRel(Y_ud).*3;
plot2(numel(plot1)+1) = plot(X_nd,Y_nd,...
    'Color',black,...
    'LineWidth',1.5,'LineStyle','-',...
    'Marker','none','MarkerSize',MarkerS,...
    'DisplayName','Regression nd 5.5');
plot2(numel(plot1)+1) = plot(X_ud,Y_ud,...
    'Color',black,...
    'LineWidth',1.5,'LineStyle','-',...
    'Marker','none','MarkerSize',MarkerS,...
    'DisplayName','Regression nd 5.5');
% regression curves - lower limits
plot2(numel(plot1)+1) = plot(X_nd,Y_nd-u_Fx_nd,...
    'Color',gray1,...
    'LineWidth',1.,'LineStyle','--',...
    'Marker','none','MarkerSize',MarkerS,...
    'DisplayName','Regression nd 5.5');
plot2(numel(plot1)+1) = plot(X_ud,Y_ud-u_Fx_ud,...
    'Color',gray1,...
    'LineWidth',1.,'LineStyle','--',...
    'Marker','none','MarkerSize',MarkerS,...
    'DisplayName','Regression nd 5.5');
% regression curves - upper limits
plot2(numel(plot1)+1) = plot(X_nd,Y_nd+u_Fx_nd,...
    'Color',gray1,...
    'LineWidth',1.,'LineStyle','--',...
    'Marker','none','MarkerSize',MarkerS,...
    'DisplayName','Regression nd 5.5');
plot2(numel(plot1)+1) = plot(X_ud,Y_ud+u_Fx_ud,...
    'Color',gray1,...
    'LineWidth',1.,'LineStyle','--',...
    'Marker','none','MarkerSize',MarkerS,...
    'DisplayName','Regression nd 5.5');

% LINE UP
fMakeXgrid(0.5:0.5:1.5,[0.,2.],0.5);
fMakeYgrid([0,2],0.5:0.5:1.5,0.5);
% Create xlabel
xlabel('b_* / h_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Grain-related flow velocity F_* [-]',...
    'FontSize',fontS,...
    'FontName','Arial');
annotation(figure1,'textbox',...
        [0.858 yPos  0.4 0.1],... % [x_begin y_begin length height]org: 0.585 yPos  0.4 0.1
        'String',{'b)'},...
        'FontName','Arial','FontSize',fontS,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');

% Make graph descriptoins
hnd = text(0.75,0.83, 'No deposit',...
    'FontName','Arial','FontSize',fontS);
set(hnd, 'rotation', 40.53)

hd = text(1.15,0.62, 'With deposit',...
    'FontName','Arial','FontSize',fontS);
set(hd, 'rotation', 20.3)

%% WRITE
if write2disc
    cd('UnsteadyFigures');
    export_fig abhFxHy.png -png
    export_fig abhFxHy.eps -eps
    cd ..
    disp('Figure (abhFxHy) written to disc (unsteady figures folder).');
    close all;
end

