function[] = fPlot_ah_FrDxHyMec(ah_HyMec, Fx_HyMec, nax_HyM, ...
                                err_Fx, err_ahx, write2disc)
%% PREAMBLE
scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 42; % best for 1x1: 46
MarkerS = 20;
CapS = 20;
reg = 1; % case 0: errorbars// case 1: regression lines
gray0 = [0.4 0.4 0.4];
gray1 = [0.85 0.85 0.85]; 
black = [0. 0. 0.]; 

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'v','^','diamond','o','<','square','>','none'};
lStyles = {'none','-',':','-.','--'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(3) scrsz(3)/1.3 scrsz(3)]);

axes1 = axes('Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0.:0.25:1.5,...
    'XTickLabel',{'0.00','0.25','0.50','0.75','1.00','1.25','1.50'},...
    'YTick',0.:0.5:2,...
    'YTickLabel',{'0.0','0.5','1.0','1.5','2.0'},...
    'LineWidth', 1.5);
% 
hold(axes1,'all');
box(axes1,'on');
grid(axes1,'off');

xlim(axes1,[0. 1.5]);
ylim(axes1,[0. 2]);


plot1(1) = plot(ah_HyMec(:,1),Fx_HyMec(:,1),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'LineStyle','none',...
    'DisplayName',['a_* = ', num2str(nax_HyM(1),'%-1.2f') ]);
plot1(numel(plot1)+1) = plot(ah_HyMec(:,2),Fx_HyMec(:,2),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'MarkerFaceColor',gray1,...
    'LineStyle','none',...
    'DisplayName',['a_* = ', num2str(nax_HyM(2),'%-1.2f') ]);
plot1(numel(plot1)+1) = plot(ah_HyMec(:,3),Fx_HyMec(:,3),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'MarkerFaceColor',gray0,...
    'LineStyle','none',...
    'DisplayName',['a_* = ', num2str(nax_HyM(3),'%-1.2f')]);

lgnd = legend(axes1,'show','Location','NorthWest');

if reg
    % make regression lines
    p1 = [1.251, 1.351, 1.451];
    p2 = [-0.2097, -0.1091, -0.008437];
    Xreg = 0.35:0.01:1.36;
    YregMin = p1(1).*Xreg+p2(1);
    YregMea = p1(2).*Xreg+p2(2);
    YregMax = p1(3).*Xreg+p2(3);

    plot1(numel(plot1)+1) = plot(Xreg,YregMea,...
        'Color',black,...
        'LineWidth',1.5,'LineStyle',lStyles{1,2},...
        'Marker','none',...
        'DisplayName','Regression mean');
    plot1(numel(plot1)+1) = plot(Xreg,YregMin,...
        'Color',gray0+0.2,...
        'LineWidth',1.5,'LineStyle','--',...
        'Marker','none',...
        'DisplayName','Regression min');
    plot1(numel(plot1)+1) = plot(Xreg,YregMax,...
        'Color',gray0+0.2,...
        'LineWidth',1.5,'LineStyle','--',...
        'Marker','none',...
        'DisplayName','Regression max');
else
    plot1(1) = errorbar(ah_HyMec(:,1),Fx_HyMec(:,1),...
        -err_Fx(:,1),err_Fx(:,1),-err_ahx(:,1),err_ahx(:,1),...
        'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
        'MarkerEdgeColor',black,...
        'Color',black+0.8,...
        'LineStyle','none',...
        'CapSize',CapS,...
        'DisplayName',['a_* = ', num2str(nax_HyM(1),'%-1.2f') ]);
    plot1(numel(plot1)+1) = errorbar(ah_HyMec(:,2),Fx_HyMec(:,2),...
        -err_Fx(:,2),err_Fx(:,2),-err_ahx(:,2),err_ahx(:,2),...
        'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
        'MarkerEdgeColor',black,...
        'MarkerFaceColor',gray1,...
        'Color',gray1-0.15,...
        'LineStyle','none',...
        'CapSize',CapS,...
        'DisplayName',['a_* = ', num2str(nax_HyM(2),'%-1.2f') ]);
    plot1(numel(plot1)+1) = errorbar(ah_HyMec(:,3),Fx_HyMec(:,3),...
        -err_Fx(:,3),err_Fx(:,3),-err_ahx(:,3),err_ahx(:,3),...
        'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
        'MarkerEdgeColor',black,...
        'MarkerFaceColor',gray0,...
        'Color',black,...
        'LineStyle','none',...
        'CapSize',CapS,...
        'DisplayName',['a_* = ', num2str(nax_HyM(3),'%-1.2f')]);
end
%set(lgnd,'TextColor',gray0,'EdgeColor',[1 1 1]);
% for i = 1:numel(ah_dsp55(1,:)) %second plot necessary as errorbar destroys legend
%     plot1(numel(plot1)+i) = errorbar(ah_dsp55(:,i),the_dsp55(:,i),...
%         -u_the_dsp(:,i),u_the_dsp(:,i),-u_ah_dsp(:,i),u_ah_dsp(:,i),...
%         'Marker',mStyles{1,i},'MarkerSize',MarkerS,...
%         'MarkerEdgeColor',black,...
%         'Color',gray1,...
%         'LineStyle','none',...
%         'CapSize',CapS,...
%         'DisplayName',['f = ', num2str(nax(i),'%-1.2f')]);
% end



% LINE UP
fMakeXgrid(0.25:0.25:1.25,[0.,2],0.5);
fMakeYgrid([0,1.5],0.5:0.5:1.5,0.5);
% Create xlabel
xlabel('a_* / h_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Grain-related flow velocity F_* [-]',...
    'FontSize',fontS,...
    'FontName','Arial');

if write2disc
    cd('UnsteadyFigures');
    export_fig ahFxHyMec.png -png
    export_fig ahFxHyMec.eps -eps
    cd ..
    disp('Figure (ahFxHyMec) written to disc (unsteady figures folder).');
    close all;
end

