function[] = fPlot_fh_FrDxMec(fhxData, FxData, err_Fx, err_fhx, nf, write2disc)
%% PREAMBLE
scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 36; % best for 1x1: 46
MarkerS = 20;
CapS = 10;

gray0 = [0.4 0.4 0.4];
gray1 = [0.6 0.6 0.6]; 
black = [0. 0. 0.]; 

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'v','^','o','<','square','>','none'};
lStyles = {'none','-',':','-.','--'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(3) scrsz(3)/1.6 scrsz(3)]);

axes1 = axes('Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0:0.2:1,...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',1:0.2:2,...
    'YTickLabel',{'1.0','1.2','1.4','1.6','1.8','2.0'},...
    'LineWidth', 1.5);
% 
hold(axes1,'all');
box(axes1,'on');
grid(axes1,'off');

xlim(axes1,[0 1]);
ylim(axes1,[1 2]);

plot1(1) = plot(fhxData(:,1),FxData(:,1),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'LineStyle','none',...
    'DisplayName',['f = ', num2str(nf(1),3)]);

for i = 2:numel(nf)
    plot1(numel(plot1)+i-1) = plot(fhxData(:,i),FxData(:,i),...
        'Marker',mStyles{1,i},'MarkerSize',MarkerS,...
        'MarkerEdgeColor',black,...
        'LineStyle','none',...
        'DisplayName',['f = ', num2str(nf(i),'%-1.2f')]);
end
lgnd = legend(axes1,'show','Location','NorthWest');

for i = 1:numel(nf) %second plot necessary as errorbar destroys legend
    plot1(numel(plot1)+i) = errorbar(fhxData(:,i),FxData(:,i),...
        -err_Fx(:,i),err_Fx(:,i),-err_fhx(:,i),err_fhx(:,i),...
        'Marker',mStyles{1,i},'MarkerSize',MarkerS,...
        'MarkerEdgeColor',black,...
        'Color',gray1,...
        'LineStyle','none',...
        'CapSize',CapS,...
        'DisplayName',['f = ', num2str(nf(i),'%-1.2f')]);
end


%set(lgnd,'TextColor',gray0,'EdgeColor',[1 1 1]);
% for i = 1:numel(ah_dsp55(1,:)) %second plot necessary as errorbar destroys legend
%     plot1(numel(plot1)+i) = errorbar(ah_dsp55(:,i),the_dsp55(:,i),...
%         -u_the_dsp(:,i),u_the_dsp(:,i),-u_ah_dsp(:,i),u_ah_dsp(:,i),...
%         'Marker',mStyles{1,i},'MarkerSize',MarkerS,...
%         'MarkerEdgeColor',black,...
%         'Color',gray1,...
%         'LineStyle','none',...
%         'CapSize',CapS,...
%         'DisplayName',['f = ', num2str(nax(i),'%-1.2f')]);
% end



% LINE UP
fMakeXgrid(0.2:0.2:0.8,[1,2],0.5);
fMakeYgrid([0,1],1.2:0.2:1.8,0.5);
% Create xlabel
xlabel('f / h_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Grain-related flow velocity F_* [-]',...
    'FontSize',fontS,...
    'FontName','Arial');

if write2disc
    cd('UnsteadyFigures');
    export_fig fhFxMec.png -png
    export_fig fhFxMec.eps -eps
    cd ..
    disp('Figure (fhFxMec) written to disc (unsteady figures folder).');
    close all;
end

