function[] = fPlot_FrDx_PhiHyMec(FxData, PhiData, nax, write2disc)
%% PREAMBLE
scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 36; % best for 1x1: 46
MarkerS = 15;
CapS = 20;

gray0 = [0.4 0.4 0.4];
gray1 = [0.65 0.65 0.65]; % 3.5p
black = [0. 0. 0.]; % 5.5p

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'v','^','o','<','square','>','none'};
lStyles = {'none','-',':','-.','--'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(3) scrsz(3)/1.6 scrsz(3)]);

axes1 = axes('Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0:0.5:2,...
    'XTickLabel',{'0.0','0.5','1.0','1.5','2.0'},...
    'YTick',0:0.5*10^-3:2*10^-3,...
    'LineWidth', 1.5);
% 'YTickLabel','YTickLabel',{'','2\cdot 10^{-4}','4\cdot 10^{-4}','6\cdot 10^{-4}','8\cdot 10^{-4}'},...
hold(axes1,'all');
box(axes1,'on');
grid(axes1,'off');

xlim(axes1,[0 2]);
ylim(axes1,[0. 2*10^-3]);

u_Fx = fGetErrFrRel(FxData)*1.5;
u_Phi= fGetErrPhiRel(PhiData);

plot1(1) = plot(FxData(:,1),PhiData(:,1),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'LineStyle','none',...
    'DisplayName',['a_* = ', num2str(nax(1),3)]);


plot1(numel(plot1)+1) = plot(FxData(:,2),PhiData(:,2),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'MarkerFaceColor',gray1,...
    'LineStyle','none',...
    'DisplayName',['a_* = ', num2str(nax(2),'%-1.2f')]);

plot1(numel(plot1)+1) = plot(FxData(:,3),PhiData(:,3),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'MarkerFaceColor',gray0,...
    'LineStyle','none',...
    'DisplayName',['a_* = ', num2str(nax(3),'%-1.2f')]);

lgnd = legend(axes1,'show','Location','NorthWest');
%set(lgnd,'TextColor',gray0,'EdgeColor',[1 1 1]);
for i = 1:numel(nax) %second plot necessary as errorbar destroys legend
    plot1(numel(plot1)+i) = errorbar(FxData(:,i),PhiData(:,i),...
        -u_Phi(:,i),u_Phi(:,i),-u_Fx(:,i),u_Fx(:,i),...
        'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
        'MarkerEdgeColor',black,...
        'Color',gray1,...
        'LineStyle','none',...
        'CapSize',CapS,...
        'DisplayName',['f = ', num2str(nax(i),'%-1.2f')]);
end

% LINE UP
fMakeXgrid(0.5:0.5:1.5,[0,0.004],0.5);
fMakeYgrid([0,2],0.5*10^-3:0.5*10^-3:3*10^-3,0.5);
% Create xlabel
xlabel('Grain-related flow velocity F_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Bedload transport intensity \Phi [-]',...
    'FontSize',fontS,...
    'FontName','Arial');

if write2disc
    cd('UnsteadyFigures');
    export_fig FxPhiHyMec.png -png
    export_fig FxPhiHyMec.eps -eps
    cd ..
    disp('Figure (PhiHyMec) written to disc (unsteady figures folder).');
    close all;
end

