function[] = fPlot_FrDx_PhiClin(Fr_udp35, Fr_udp55, Fr_udf35, Fr_udf55, ...
                 Fr_ndp35, Fr_ndp55, Fr_ndf35, Fr_ndf55, ...
                  Fr_dsp55, ...
                   Phi_ud35, Phi_ud55, ...
                    Phi_ndp35, Phi_ndp55, Phi_ndf35, Phi_ndf55, ...
                     Phi_dsp55, write2disc)
%% PREAMBLE
scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 25; % best for 1x1: 46
MarkerS = 10;
yPos = 0.825; % y position of the textbox

%gray0 = [0.4 0.4 0.4];
gray35 = [0.6 0.6 0.6]; % 3.5p
black55 = [0. 0. 0.]; % 5.5p

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'+','o','diamond','v','square','pentagram','x','^','*','>','h','<','none'};
lStyles = {'none','-',':','-.','--'};

%% GET REGRESSION CURVES + UNCERTAINTIES
[X_nd35, X_nd55, X_ud35, X_ud55, X_dsp55, ...
  Y_nd35, Y_nd55, Y_ud35, Y_ud55, Y_dsp55, ...
   u_nd35, u_nd55, u_ud35, u_ud55, u_dsp55, ...
    u_nd35x,u_nd55x,u_ud35x,u_ud55x,u_dsp55x] = fRegMake_FrDx_PhiC();


figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3) scrsz(4)/1.6]);
% 1 x 2 FIGURE with a) & b)
%% SUBPLOT a) no deposit
subplot1 = subplot(1,2,1,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0:0.5:2,...
    'XTickLabel',{'0.0','0.5','1.0','1.5','2.0'},...
    'LineWidth', 1.5);
%     'YTickLabel',{'10^{-3}','10^{-2}','10^{-1}'},...
%     'YTick',0.001:0.02:0.12,...
%     'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
%     'XTick',0.0:0.2:1,...
set(subplot1,'MinorGridColor',...
    [0.2 0.2 0.2],... % color
    'MinorGridLineStyle','-',...%'XMinorTick','on','XScale','log',...
    'YMinorTick','on');  

hold(subplot1,'all');
box(subplot1,'on');
grid(subplot1,'on');

xlim(subplot1,[0 2]);
ylim(subplot1,[0.0001 0.1]);

plot1(1) = plot(Fr_ndp55,Phi_ndp55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,7},'MarkerSize',MarkerS,...
    'DisplayName','pressurized');

plot1(numel(plot1)+1) = plot(Fr_ndf55,Phi_ndf55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName','free surface');



% Legend order plotting
% plot non-constricted

% make legend entries for slope colours
% plot1(numel(plot1)+1) = plot(10:1:11,10:1:11,...
%     'Color',gray35+0.15,...
%     'LineWidth',20,'LineStyle',lStyles{1,2},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName','   I =  3.5 %');
% plot1(numel(plot1)+1) = plot(10:1:11,10:1:11,...
%     'Color',black55,...
%     'LineWidth',20,'LineStyle',lStyles{1,2},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName','   I =  5.5 %');
lgnd = legend(subplot1,'show','Location','SouthEast');
set(lgnd,'FontSize',fontS+2,'FontName','Arial Narrow');

% plot1(1) = plot(Fr_ndp35,Phi_ndp35,...
%     'Color',gray35,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,1},...
%     'Marker',mStyles{1,7},'MarkerSize',MarkerS,...
%     'DisplayName','no deposit, pressurized');

% plot1(numel(plot1)+1) = plot(Fr_ndf35,Phi_ndf35,...
%     'Color',gray35,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,1},...
%     'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
%     'DisplayName','no deposit, free surface');

% regression curves - main
% plot1(numel(plot1)+1) = plot(X_nd35,Y_nd35,...
%     'Color',gray35,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,2},...
%     'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
%     'DisplayName','Regression nd 3.5');
plot1(numel(plot1)+1) = plot(X_nd55,Y_nd55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
    'DisplayName','Regression nd 5.5');
% regression curves - lower limits
% plot1(numel(plot1)+1) = plot(X_nd35+u_nd35x,Y_nd35-u_nd35,...
%     'Color',gray35,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,4},...
%     'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
%     'DisplayName','Regression nd 3.5');
plot1(numel(plot1)+1) = plot(X_nd55+u_nd55x,Y_nd55-u_nd55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
    'DisplayName','Regression nd 5.5');
% regression curves - upper limits
% plot1(numel(plot1)+1) = plot(X_nd35-u_nd35x,Y_nd35+u_nd35,...
%     'Color',gray35,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,4},...
%     'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
%     'DisplayName','Regression nd 3.5');
plot1(numel(plot1)+1) = plot(X_nd55-u_nd55x,Y_nd55+u_nd55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
    'DisplayName','Regression nd 5.5');

% Create xlabel
xlabel('Flow intensity F_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Bedload transport intensity \Phi [-]',...
    'FontSize',fontS,...
    'FontName','Arial');
annotation(figure1,'textbox',...
        [0.14 yPos  0.4 0.1],... % [x_begin y_begin length height]org:0.425 yPos  0.4 0.1
        'String',{'a)'},...
        'FontName','Arial','FontSize',fontS,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');

%% SUBPLOT b) with deposit
subplot2 = subplot(1,2,2,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0:0.5:2,...
    'XTickLabel',{'0.0','0.5','1.0','1.5','2.0'},...
    'LineWidth', 1.5);
%     'YTickLabel',{'10^{-3}','10^{-2}','10^{-1}'},...
%     'YTick',0.001:0.02:0.12,...
% 'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
%     'XTick',0.0:0.2:1,...
set(subplot2,'MinorGridColor',...
    [0.2 0.2 0.2],... % color
    'MinorGridLineStyle','-',...%'XMinorTick','on','XScale','log',...
    'YMinorTick','on');  

hold(subplot2,'all');
box(subplot2,'on');
grid(subplot2,'on');

xlim(subplot2,[0 2]);
ylim(subplot2,[0.0001 0.1]);

plot2(1) = plot(Fr_udp55,Phi_ud55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,5},'MarkerSize',MarkerS+5,...
    'DisplayName','pressurized');

plot2(numel(plot2)+1) = plot(Fr_udf55,Phi_ud55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS+2,...
    'DisplayName','free surface');

plot2(numel(plot2)+1) = plot(Fr_dsp55,Phi_dsp55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS+5,...%'MarkerFaceColor',gray35+0.2,...
    'DisplayName','pressurized\newline overspill');

lgnd = legend(subplot2,'show',...
        '1.i pressurized',...
        '1.i free surface',...
        '1.ii',...
        'Location','SouthEast');
set(lgnd,'FontSize',fontS+2,'FontName','Arial Narrow');
% plot2(numel(plot1)+1) = plot(Fr_udp35,Phi_ud35,...
%     'Color',gray35,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,1},...
%     'Marker',mStyles{1,5},'MarkerSize',MarkerS+5,...
%     'DisplayName','i) small deposit pressurized');

% plot2(numel(plot1)+1) = plot(Fr_udf35,Phi_ud35,...
%     'Color',gray35,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,1},...
%     'Marker',mStyles{1,4},'MarkerSize',MarkerS+2,...
%     'DisplayName','i) small deposit, free surface');

% regression curves - main
% plot2(numel(plot1)+1) = plot(X_ud35,Y_ud35,...
%     'Color',gray35,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,2},...
%     'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
%     'DisplayName','Regression ud 3.5');
plot2(numel(plot2)+1) = plot(X_ud55,Y_ud55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
    'DisplayName','Regression ud 5.5');
plot2(numel(plot2)+1) = plot(X_dsp55,Y_dsp55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
    'DisplayName','Regression dsp 5.5');
% regression curves - lower limits
% plot2(numel(plot1)+1) = plot(X_ud35+u_ud35x,Y_ud35-u_ud35,...
%     'Color',gray35,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,4},...
%     'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
%     'DisplayName','Regression ud 3.5');
plot2(numel(plot2)+1) = plot(X_ud55+u_ud55x,Y_ud55-u_ud55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
    'DisplayName','Regression ud 5.5');
plot2(numel(plot2)+1) = plot(X_dsp55+u_dsp55x,Y_dsp55-u_dsp55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
    'DisplayName','Regression dsp 5.5');
% regression curves - upper limits
% plot2(numel(plot1)+1) = plot(X_ud35-u_ud35x,Y_ud35+u_ud35,...
%     'Color',gray35,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,4},...
%     'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
%     'DisplayName','Regression ud 3.5');
plot2(numel(plot2)+1) = plot(X_ud55-u_ud55x,Y_ud55+u_ud55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
    'DisplayName','Regression ud 5.5');
plot2(numel(plot2)+1) = plot(X_dsp55-u_dsp55x,Y_dsp55+u_dsp55,...
    'Color',black55,...
    'LineWidth',1.5,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,13},'MarkerSize',MarkerS,...
    'DisplayName','Regression dsp 5.5');

%fMakeXgrid(0.2:0.2:0.8,[0,12],0.5);
%fMakeYgrid([0,1],0.02:0.02:0.10,0.5);

% Create xlabel
xlabel('Flow intensity F_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Bedload transport intensity \Phi [-]',...
    'FontSize',fontS,...
    'FontName','Arial');

annotation(figure1,'textbox',...
        [0.585 yPos  0.4 0.1],... % [x_begin y_begin length height]org: 0.858 yPos  0.4 0.1
        'String',{'b)'},...
        'FontName','Arial','FontSize',fontS,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');
% annotation(figure1,'textbox',...
%         [0.83 yPos-0.66  0.4 0.1],... % [x_begin y_begin length height]org: 0.625 yPos  0.4 0.1
%         'String',{'&'},...
%         'FontName','Arial','FontSize',fontS-7,...
%         'FitBoxToText','on',...
%         'LineStyle','none');
    
if write2disc
    cd('UnsteadyFigures');
    export_fig FxPhiClin.png -png
    export_fig FxPhiClin.jpg -jpg
    % export_fig FxPhiC.eps -eps % not used, powerpoint maniupulations!
    cd ..
    disp('Figure (compFrDxPhiC) written to disc (unsteady figures folder).');
    close all;
end

