function[] = fPlot_Q_TheSJ(Q_dsp55, Q_mec, Q_HyMec, ...
                            the_dsp55, the_mec, the_HyMec, ...
                            nax_dsp, nax_HyM, write2disc)
%% PREAMBLE
scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 36; % best for 1x1: 46
MarkerS = 20;
CapS = 20;

reg = 1; % 0 -> no regression line, 1 -> regression line

gray0 = [0.4 0.4 0.4];
gray1 = [0.65 0.65 0.65]; % 3.5p
black = [0. 0. 0.]; % 5.5p

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'v','^','diamond','o','<','square','>','none'};
lStyles = {'none','--',':','-.','-'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(3) scrsz(3)/1.6 scrsz(3)]);

axes1 = axes('Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0.003:0.002:0.011,...
    'XTickLabel',{'3.0','5.0','7.0','9.0','11.0'},...
    'YTick',0:0.5:2,...
    'YTickLabel',{'0.0','0.5','1.0','1.5','2.0'},...
    'LineWidth', 1.5);

hold(axes1,'all');
box(axes1,'on');
grid(axes1,'off');

xlim(axes1,[0.003 0.011]);
ylim(axes1,[0. 2]);

eps_Q = 0.02;
u_Q_dsp = Q_dsp55.*eps_Q;
u_the_dsp = fGetErrTheRel(the_dsp55);
u_Q_HyMec = Q_HyMec.*eps_Q;
u_the_HyMec = fGetErrTheRel(the_HyMec);
u_Q_mec = Q_mec.*eps_Q;
u_the_mec = fGetErrTheRel(the_mec);
%% PLOT
plot1(1) = plot(Q_dsp55(:,1),the_dsp55(:,1),...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'LineStyle','none',...
    'DisplayName',['Hyd. a_* = ', num2str(nax_dsp(1),'%-1.2f') ]);
plot1(numel(plot1)+1) = plot(Q_dsp55(:,2),the_dsp55(:,2),...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'MarkerFaceColor',gray1,...
    'LineStyle','none',...
    'DisplayName',['Hyd. a_* = ', num2str(nax_dsp(2),'%-1.2f') ]);
plot1(numel(plot1)+1) = plot(Q_dsp55(:,3),the_dsp55(:,3),...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'MarkerFaceColor',gray0,...
    'LineStyle','none',...
    'DisplayName',['Hyd. a_* = ', num2str(nax_dsp(3),'%-1.2f')]);

plot1(numel(plot1)+1) = plot(Q_mec,the_mec,...
    'Marker',mStyles{1,5},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'LineStyle','none',...
    'DisplayName',['Mec. f_{} = 1.75']);

plot1(numel(plot1)+1) = plot(Q_HyMec(:,1),the_HyMec(:,1),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'LineStyle','none',...
    'DisplayName',['Com. a_* = ', num2str(nax_HyM(1),'%-1.2f')]);
plot1(numel(plot1)+1) = plot(Q_HyMec(:,2),the_HyMec(:,2),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'MarkerFaceColor',gray1,...
    'LineStyle','none',...
    'DisplayName',['Com. a_* = ', num2str(nax_HyM(2),'%-1.2f')]);
plot1(numel(plot1)+1) = plot(Q_HyMec(:,3),the_HyMec(:,3),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'MarkerFaceColor',gray0,...
    'LineStyle','none',...
    'DisplayName',['Com. a_* = ', num2str(nax_HyM(3),'%-1.2f')]);



% make regression lines
if reg
    % HY-MEC
    p1 = 90.63;
    p2 = -0.2623;
    % a* = inf
    Xreg = 0.006:0.0001:0.0103;
    Yreg = p1.*Xreg+p2;
    plot1(numel(plot1)+1) = plot(Xreg,Yreg,...
        'Color',black,...
        'LineWidth',1.5,'LineStyle',lStyles{1,2},...
        'Marker','none',...
        'DisplayName','Regression  curves ');
    lgnd = legend(axes1,'show','Location','NorthEast');
    % HYD
    p1 = [-366.7, -556.7, -206.7];
    p2 = [1.877, 2.999, 1.903];
    % a* = 2.98
    Xreg = 0.0035:0.0001:0.00515;
    Yreg = p1(1).*Xreg+p2(1);
    plot1(numel(plot1)+1) = plot(Xreg,Yreg,...
        'Color',gray1+0.15,...
        'LineWidth',1.5,'LineStyle',lStyles{1,2},...
        'Marker','none',...
        'DisplayName','reg');
    % a* = 3.14
    Xreg = 0.0031:0.0001:0.0054;
    Yreg = p1(2).*Xreg+p2(2);
    plot1(numel(plot1)+1) = plot(Xreg,Yreg,...
        'Color',gray1,...
        'LineWidth',1.5,'LineStyle',lStyles{1,2},...
        'Marker','none',...
        'DisplayName','reg');
    % a* = 3.44
    Xreg = 0.0032:0.0001:0.0089;
    Yreg = p1(3).*Xreg+p2(3);
    plot1(numel(plot1)+1) = plot(Xreg,Yreg,...
        'Color',gray0,...
        'LineWidth',1.5,'LineStyle',lStyles{1,2},...
        'Marker','none',...
        'DisplayName','reg');
    % MEC
    p1 = -86.39;
    p2 = 1.473;
    % a* = inf
    Xreg = 0.0032:0.0001:0.0073;
    Yreg = p1.*Xreg+p2;
    plot1(numel(plot1)+1) = plot(Xreg,Yreg,...
        'Color',gray1+0.15,...
        'LineWidth',1.5,'LineStyle',lStyles{1,2},...
        'Marker','none',...
        'DisplayName','reg');
else
    lgnd = legend(axes1,'show','Location','NorthEast');
end

% errorbar HY
plot1(numel(plot1)+1) = errorbar(Q_dsp55(:,1),the_dsp55(:,1),...
    -u_the_dsp(:,1),u_the_dsp(:,1),-u_Q_dsp(:,1),u_Q_dsp(:,1),...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'Color',black,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName',['f = ', num2str(nax_dsp(1),'%-1.2f')]);

plot1(numel(plot1)+1) = errorbar(Q_dsp55(:,2),the_dsp55(:,2),...
    -u_the_dsp(:,2),u_the_dsp(:,2),-u_Q_dsp(:,2),u_Q_dsp(:,2),...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',gray1,...
    'Color',gray1,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName',['f = ', num2str(nax_dsp(2),'%-1.2f')]);

plot1(numel(plot1)+1) = errorbar(Q_dsp55(:,3),the_dsp55(:,3),...
    -u_the_dsp(:,3),u_the_dsp(:,3),-u_Q_dsp(:,3),u_Q_dsp(:,3),...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',gray0,...
    'Color',gray0,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName',['f = ', num2str(nax_dsp(3),'%-1.2f')]);

% errorbar HYMEC
plot1(numel(plot1)+1) = errorbar(Q_HyMec(:,1),the_HyMec(:,1),...
    -u_the_HyMec(:,1),u_the_HyMec(:,1),-u_Q_HyMec(:,1),u_Q_HyMec(:,1),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'Color',black,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName',['f = ', num2str(nax_HyM(1),'%-1.2f')]);

plot1(numel(plot1)+1) = errorbar(Q_HyMec(:,2),the_HyMec(:,2),...
    -u_the_HyMec(:,2),u_the_HyMec(:,2),-u_Q_HyMec(:,2),u_Q_HyMec(:,2),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',gray1,...
    'Color',gray1,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName',['f = ', num2str(nax_HyM(2),'%-1.2f')]);

plot1(numel(plot1)+1) = errorbar(Q_HyMec(:,3),the_HyMec(:,3),...
    -u_the_HyMec(:,3),u_the_HyMec(:,3),-u_Q_HyMec(:,3),u_Q_HyMec(:,3),...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',gray0,...
    'Color',gray0,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName',['f = ', num2str(nax_HyM(3),'%-1.2f')]);

% errorbar MEC
plot1(numel(plot1)+1) = errorbar(Q_mec, the_mec, ...
    -u_the_mec, u_the_mec, -u_Q_mec, u_Q_mec, ...
    'Marker',mStyles{1,5},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'Color',black,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName',['f = 1.75']);

% LINE UP
fMakeXgrid(0.005:0.002:0.009,[0,2],0.5);
fMakeYgrid([0,0.011],0.5:0.5:1.5,0.5);
% Create xlabel
xlabel('Discharge Q [10^{-3} m^3/s]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Q_b(barrier) / Q_b(Smart & Jaeggi) [-]',...
    'FontSize',fontS,...
    'FontName','Arial');

if write2disc
    cd('UnsteadyFigures');
    export_fig QTheSJ.png -png
    export_fig QTheSJ.jpg -jpg % use Powerpoint manipulation
    cd ..
    disp('Figure (QTheSmartJaeggi) written to disc (unsteady figures folder).');
    close all;
end

