function[] = fPlot_FrDx_PhiNC(Fr_nc, Fr_theo, errFr_nc, ...
         Phi_nc, Phi_SM, Phi_RIC, Phi_REC, errPhi_nc, write2disc)

scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 36; % best for 1x1: 46
MarkerS = 20;
CapS = 15;

gray0 = [0.4 0.4 0.4];
gray1 = [0.6 0.6 0.6];
black = [0. 0. 0.];

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'+','o','diamond','v','square','pentagram','x','^','*','>','h','<','none'};
lStyles = {'none','-','--','-.',':'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(3) scrsz(3)/1.6 scrsz(3)]);


axes1 = axes('Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',2.2:0.2:3.2,...
    'XTickLabel',{'2.2','2.4','2.6','2.8','3.0','3.2'},...
    'YTick',0:0.1:0.6,...
    'YTickLabel',{'0.0','0.1','0.2','0.3','0.4','0.5','0.6'},...
    'LineWidth', 1.5);

% XTickLabel',{'1.0','1.5','2.0','2.5','3.0','3.5','4.0'},...    
% 'XTickLabel',{'10^{-1}','10^{0}','10^{1}','10^{2}'},...
%     'XTickLabel',{'0.0','0.5','1.0','1.5','2.0'},...
%     'YTick',0:0.1:0.5,...
%     'YTickLabel',{'0.0','0.1','0.2','0.3','0.4','0.5'},...

% set(axes1,'MinorGridColor',...
%     [0.2 0.2 0.2],... % color
%     'MinorGridLineStyle','-',...%'XMinorTick','on','XScale','log',...
%     'YMinorTick','on','YScale','log');   

hold(axes1,'all');
box(axes1,'on');
grid(axes1,'off');

xlim(axes1,[2.2 3.2]);
ylim(axes1,[0. 0.6]);

% % % plot UNSTEADY Pressure
% plot1(1) = plot(Fr_u,Phi_u,...
%     'Color',gray0,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,1},...
%     'Marker',mStyles{1,5},'MarkerSize',MarkerS,...
%     'DisplayName','Unsteady pressurized');
% 
% % plot UNSTEADY Free surface
% plot1(numel(plot1)+1) = plot(Fr_u_fs,Phi_u,...
%     'Color',gray0,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,1},...
%     'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
%     'DisplayName','Unsteady free surface');
% 
% % plot STEADY Pressure
% plot1(numel(plot1)+1) = plot(Fr_s,Phi_s,...
%     'Color',black,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,1},...
%     'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
%     'DisplayName','Steady pressurized');
% 
% % plot STEADY Free surface
% plot1(numel(plot1)+1) = plot(Fr_s_fs,Phi_s,...
%     'Color',black,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,1},...
%     'Marker',mStyles{1,7},'MarkerSize',MarkerS,...
%     'DisplayName','Steady free surface');

% Legend order plotting
% plot non-constricted
plot1(1) = plot(Fr_nc(:,3),Phi_nc(:,3),...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'LineStyle','none',...
    'DisplayName','Data non-constricted (steady)');
% plot Smart Jaegggi
plot1(numel(plot1)+1) = plot(Fr_theo(:,3),Phi_SM(:,3),...
    'Color',black,...
    'LineWidth',1.5,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
    'DisplayName','Smart & Jaeggi (1983)');
% plot Rickenmann
% plot1(numel(plot1)+1) = plot(Fr_theo(:,3),Phi_RIC(:,3),...
%     'Color',black,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,3},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName','Rickenmann (1991)');
% % plot Recking
% plot1(numel(plot1)+1) = plot(Fr_theo(:,1),Phi_REC(:,1),...
%     'Color',black,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,4},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName',' Recking (2013)');

% make legend entries for slope colours
% plot1(numel(plot1)+1) = plot(10:1:11,10:1:11,...
%     'Color',black,...
%     'LineWidth',20,'LineStyle',lStyles{1,2},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName','   I =  2.0 %');
% plot1(numel(plot1)+1) = plot(10:1:11,10:1:11,...
%     'Color',gray1+0.1,...
%     'LineWidth',20,'LineStyle',lStyles{1,2},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName','   I =  3.5 %');
% plot1(numel(plot1)+1) = plot(10:1:11,10:1:11,...
%     'Color',black,...
%     'LineWidth',20,'LineStyle',lStyles{1,2},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName','   I =  5.5 %');
lgnd = legend(axes1,'show','Location','NorthWest');
%set(lgnd,'TextColor',gray0,'EdgeColor',[1 1 1]);
plot1(1) = errorbar(Fr_nc(:,3),Phi_nc(:,3),...
    -errPhi_nc(:,3),errPhi_nc(:,3),-errFr_nc(:,3),errFr_nc(:,3),...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerEdgeColor',black,...
    'Color',black,...
    'LineStyle','none',...
    'CapSize',CapS,...
    'DisplayName','Data non-constricted (steady)');
% remaining slopes
% plot1(numel(plot1)+1) = errorbar(Fr_nc(:,2),Phi_nc(:,2),...
%     -errPhi_nc(:,2),errPhi_nc(:,2),-errFr_nc(:,2),errFr_nc(:,2),...
%     'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
%     'MarkerEdgeColor',gray1,...
%     'Color',gray1,...
%     'LineStyle','none',...
%     'CapSize',CapS,...
%     'DisplayName','Steady, non-constricted I=3.5 \%');
% 
% plot1(numel(plot1)+1) = plot(Fr_theo(:,2),Phi_SM(:,2),...
%     'Color',gray1,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,2},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName','Smart & Jaeggi (1983) I=3.5 %');
% 
% 
% plot1(numel(plot1)+1) = plot(Fr_theo(:,2),Phi_RIC(:,2),...
%     'Color',gray1,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,3},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName','Rickenmann (1991) I=3.5 %');



% plot1(numel(plot1)+1) = plot(Fr_theo(:,2),Phi_REC(:,2),...
%     'Color',gray1,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,4},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName','Recking (2013) I=3.5 %');
% plot1(numel(plot1)+1) = plot(Fr_theo(:,3),Phi_REC(:,3),...
%     'Color',gray0,...
%     'LineWidth',1.5,'LineStyle',lStyles{1,4},...
%     'Marker',mStyles{1,end},'MarkerSize',MarkerS,...
%     'DisplayName','Recking (2013) I=5.5 %');



% yPos = 0.815;
% annotation(figure1,'textbox',...
%         [0.25 yPos  0.4 0.1],... % [x_begin y_begin length height]
%         'String',{['Free',char(10), 'surface']},...
%         'FontName','Arial','FontSize',fontS,...
%         'FitBoxToText','on',...
%         'FontAngle','italic',...
%         'Color',gray0+0.2,...
%         'EdgeColor',gray0,...
%         'LineStyle','none');

% LINE UP
fMakeXgrid(2.4:0.2:3,[0,0.6],0.5);
fMakeYgrid([2.2,3.2],0.1:0.1:0.5,0.5);

% Create xlabel
xlabel('Grain-related flow velocity F_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Bedload transport intensity \Phi [-]',...
    'FontSize',fontS,...
    'FontName','Arial');



if write2disc
    cd('UnsteadyFigures');
    export_fig FxPhiNC.png -png
    export_fig FxPhiNC.eps -eps
    cd ..
    disp('Figure (compFrDxPhiNC) written to disc (unsteady figures folder).');
    close all;
end

